#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : groupcheck
Version  : 9504243495745808682135899
Release  : 1
URL      : https://github.com/ostroproject/groupcheck/archive/95e04ae24d3e495b7458a08d6fcb8c2a1358e99e.tar.gz
Source0  : https://github.com/ostroproject/groupcheck/archive/95e04ae24d3e495b7458a08d6fcb8c2a1358e99e.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-2.1
Requires: groupcheck-bin
BuildRequires : pkgconfig(libsystemd)

%description


%package bin
Summary: bin components for the groupcheck package.
Group: Binaries

%description bin
bin components for the groupcheck package.


%prep
%setup -q -n groupcheck-95e04ae24d3e495b7458a08d6fcb8c2a1358e99e

%build
export LANG=C
export SOURCE_DATE_EPOCH=1491403445
unset LD_AS_NEEDED
%reconfigure --disable-static
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1491403445
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/groupcheck
